### ISSUE TITLE
Weird pink dot near the clock?

### ISSUE THREAD

**Issue by katedering** [sonofhawk01/WorldClock#1]
![2018-02-08_02 23 29](https://user-images.githubusercontent.com/26468141/35960282-16bff490-0c77-11e8-99c7-249df9bf2980.png)

See attached image. I'm thinking that it is supposed to be a sun or moon or something? Using 1.2.1 beta for MC 1.12.0

**Comment by katedering** [comment]
![2018-02-08_02 25 47](https://user-images.githubusercontent.com/26468141/35960381-7141b3fe-0c77-11e8-952a-e92b54d1df06.png)

There's a white dot too.

**Comment by katedering** [comment]
And without resource packs, still there.:
![2018-02-08_02 27 02](https://user-images.githubusercontent.com/26468141/35960418-8daa4e98-0c77-11e8-96f5-ef494ab1fac2.png)

**Comment by digitalshadowhawk** [comment]
That's how it's supposed to look, though I'll admit it matches the digital clock format better than it matches analog.

**Comment by katedering** [comment]
What exactly do they mean?


And would there be a way to toggle them off or on?
